[versions]

##### Dependency versions #####

#Annotation
annotation = '1.6.0'

#AppCompat
appCompat = '1.6.1'

#Coil
coil = '2.3.0'

#Compose
activity = '1.7.2'
compiler = '1.4.8'
composeCore = '1.6.0-alpha01'
material3 = '1.2.0-alpha03'

#Coroutines
coroutines = '1.7.2'

#DataStore
dataStore = '1.1.0-alpha04'

#Quality checking
#Detekt
detekt = '1.23.0'

#Ktlint
ktlint = '0.49.1'
ktlintPlugin = '11.4.0'

#Gradle
gradle = '8.0.2'

#Koin
koin = '3.4.2'

#Kotlin
kotlin = '1.9.0'

#Kover
kover = '0.7.2'

#KSP
ksp = '1.9.0-1.0.11'

#Ktx
ktxCore = '1.11.0-beta01'

#LeakCanary
leakCanary = '2.12'

#Lifecycle
lifecycle = '2.6.1'

#Material design
materialDesign = '1.9.0'

#OkHttp
okHttp = '5.0.0-alpha.11'

#Retrofit
retrofit = '2.9.0'
serializationConverter = '1.0.0'

#Room
room = '2.5.2'

#Serialization
serialization = '1.5.1'

#Timber
timber = '5.0.1'

#Views/ViewGroups
#ConstraintLayout
constraintLayout = '2.1.4'

#RecyclerView
recyclerView = '1.3.0'

#SwipeRefreshLayout
swipeRefreshLayout = '1.2.0-alpha01'

##### Test dependency versions #####

#Arch
archTest = '2.2.0'

#Espresso
espresso = '3.5.1'

#Jacoco
jacoco = '0.8.10'

#JUnit
junit = '4.13.2'
junitAndroidX = '1.1.5'
junit5 = '5.9.3'

#Kotest
kotest = '5.6.1'

#Mockk
mockkVersion = '1.13.5'

#Core
testCore = '1.6.0-alpha01'

##### Libraries #####

[libraries]

#Annotation
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }

#APIConnector
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofitSerializationConverter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "serializationConverter" }

#AppCompat
appCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }

#Coil
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }

#Compose
activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
animationCompose = { group = "androidx.compose.animation", name = "animation", version.ref = "composeCore" }
foundationCompose = { group = "androidx.compose.foundation", name = "foundation", version.ref = "composeCore" }
lifecycleCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
materialCompose = { group = "androidx.compose.material", name = "material", version.ref = "composeCore" }
material3Compose = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
materialIconsCoreCompose = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "composeCore" }
materialIconsExtendedCompose = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeCore" }
runtimeAndroidCompose = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "composeCore" }
runtimeCompose = { group = "androidx.compose.runtime", name = "runtime", version.ref = "composeCore" }
uiCompose = { group = "androidx.compose.ui", name = "ui", version.ref = "composeCore" }
uiToolingCompose = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeCore" }
uiToolingPreviewCompose = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeCore" }

#Core
ktxCore = { group = "androidx.core", name = "core-ktx", version.ref = "ktxCore" }

#DataStore
dataStore = { group = "androidx.datastore", name = "datastore", version.ref = "dataStore" }

#Espresso
idlingResourceEspresso = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espresso" }

#Koin
koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }

#Leak canary
leakCanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakCanary" }

#Lifecycle section
lifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleViewmodelKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

#Logging section
okhttpLoggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okHttp" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

#Material design
materialDesign = { group = "com.google.android.material", name = "material", version.ref = "materialDesign" }

#Room
room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
roomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

#Serialization
jsonSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

#Views/ViewGroups
constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerView" }
swipeRefreshLayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipeRefreshLayout" }

##### Testing Section #####
#JVM
#TestCore
archTest = { group = "androidx.arch.core", name = "core-testing", version.ref = "archTest" }
testCore = { group = "androidx.test", name = "core-ktx", version.ref = "testCore" }
testRunner = { group = "androidx.test", name = "runner", version.ref = "testCore" }

#Coroutines
coroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

#Jacoco
jacoco = { group = "org.jacoco", name = "org.jacoco.core", version.ref = "jacoco" }

#JUnit
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit5 = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }

#Kotest
kotestCore = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotestProperty = { group = "io.kotest", name = "kotest-property", version.ref = "kotest" }
kotestRunner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }

#MockK
mockkAgent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockkVersion" }
mockkAndroid = { group = "io.mockk", name = "mockk-android", version.ref = "mockkVersion" }

#MockWebServer
mockWebServer = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okHttp" }

# Instrumented/UI #

#Compose
composeTestJUnit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeCore" }
composeTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeCore" }

#Espresso
espressoAccessibility = { group = "androidx.test.espresso", name = "espresso-accessibility", version.ref = "espresso" }
espressoContrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
espressoIdlingResource = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espresso" }
espressoIntents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso" }

#JUnit
junitAndroidX = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitAndroidX" }

##### Plugins #####

[plugins]
androidApplication = { id = "com.android.application", version.ref = "gradle" }
androidLibrary = { id = "com.android.library", version.ref = "gradle" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlinPlugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

##### Bundles #####

[bundles]

apiConnection = [
 "retrofit",
 "retrofitSerializationConverter"
]

compose = [
 "activityCompose",
 "animationCompose",
 "foundationCompose",
 "lifecycleCompose",
 "materialCompose",
 "material3Compose",
 "materialIconsCoreCompose",
 "materialIconsExtendedCompose",
 "runtimeAndroidCompose",
 "runtimeCompose",
 "uiCompose",
 "uiToolingPreviewCompose"
]

lifecycle = [
 "lifecycleRuntimeKtx",
 "lifecycleViewmodelKtx"
]

logging = [
 "okhttpLoggingInterceptor",
 "timber"
]

room = [
 "room",
 "roomKtx"
]

views = [
 "constraintLayout",
 "recyclerView",
 "swipeRefreshLayout"
]

# Test Bundles #

testCore = [
 "archTest",
 "testCore",
 "testRunner"
]

espressoTest = [
 "espressoAccessibility",
 "espressoContrib",
 "espressoCore",
 "espressoIdlingResource",
 "espressoIntents"
]

junit = [
 "junit",
 "junit5"
]

kotest = [
 "kotestCore",
 "kotestProperty",
 "kotestRunner"
]

mockk = [
 "mockkAgent",
 "mockkAndroid"
]