package githubprofilesearcher.caiodev.com.br.githubprofilesearcher.sections.githubUserInformationObtainment.view.viewHolder.transientItemViews

import androidx.recyclerview.widget.RecyclerView
import githubprofilesearcher.caiodev.com.br.githubprofilesearcher.databinding.EmptyViewHolderLayoutBinding

class EmptyViewHolder(itemBinding: EmptyViewHolderLayoutBinding) : RecyclerView.ViewHolder(itemBinding.root)
