package githubprofilesearcher.caiodev.com.br.githubprofilesearcher.sections.githubUserInformationObtainment.view.viewHolder.transientItemViews

import androidx.recyclerview.widget.RecyclerView
import githubprofilesearcher.caiodev.com.br.githubprofilesearcher.databinding.EndOfResultsViewHolderLayoutBinding

class EndOfResultsViewHolder(itemBinding: EndOfResultsViewHolderLayoutBinding) :
    RecyclerView.ViewHolder(itemBinding.root)
